// Grove — src/lib/types.ts
//
// PLACEHOLDER. This file is generated by scripts/gen-types.mjs
// (`npm run gen:types`), which calls the Supabase Management API and replaces
// the whole file with the `Database` type for the public schema.
//
// Until a Supabase project exists there is nothing to generate, so it
// re-exports the hand-written domain models instead. Import domain types
// from './models'; this file only keeps the generated path warm, and the
// re-exports below disappear the first time gen:types runs.
export type { Session, Participant, Note, Finding, RosterRow, FindingObserver } from './models';
