// Grove — 8.14 Independence receipt. GROVE-MASTER.md §8.14, §7 S10.
import { useState } from 'react';
import type { SyntheticEvent } from 'react';
import { Icon } from './Icon';
import { istTime } from '../lib/time';
import { loadReceiptOpen, saveReceiptOpen } from '../lib/storage';

export interface ReceiptProps {
  observers: number;
  notes: number;
  /** Synthesis time, ISO. Unknown → the timestamp clause is omitted. */
  at?: string | null;
  /** Exactly one participant. GROVE-MASTER.md §7 S10. */
  solo?: boolean;
}

/* ---------- 8.14 Independence receipt.
   Every number here is computed in APPLICATION CODE. Nothing in the receipt is
   generated by the model: a claim about how a system behaved must never be
   written by the thing it describes.
   A receipt with a gap is worthless — omit any clause whose number is unknown. */
export function Receipt({ observers, notes, at, solo }: ReceiptProps) {
  const time = istTime(at);

  // The <details> is collapsed by default and its state is remembered on the
  // device. GROVE-MASTER.md §8.14.
  const [open, setOpen] = useState<boolean>(() => loadReceiptOpen());
  const onToggle = (e: SyntheticEvent<HTMLDetailsElement>) => {
    const next = e.currentTarget.open;
    setOpen(next);
    saveReceiptOpen(next);
  };

  // Two clause groups, so the line breaks BETWEEN clauses rather than through
  // one. Below 640px they stack; above, they join with a middle dot. §10
  const head = [
    `${observers} observer${observers === 1 ? '' : 's'}`,
    `${notes} note${notes === 1 ? '' : 's'}`,
  ];
  let tail: string | null = null;

  if (solo) {
    // With one lane there is nothing to have crossed, so the lane clause is
    // omitted entirely rather than stated hollowly. GROVE-MASTER.md S10.
    if (time) tail = `synthesised at ${time} IST`;
  } else {
    head.push('written in separate lanes');
    // Omit any clause whose value is unknown — a receipt with a gap is
    // worthless, and a placeholder is worse. §8.14
    if (time) tail = `no note text crossed a lane before synthesis at ${time} IST`;
  }

  return (
    <section aria-label="How these findings were produced">
      <p className="t-receipt receipt__line">
        <span className="receipt__seg">{head.join(' · ')}</span>
        {tail && <span className="receipt__sep" aria-hidden="true"> · </span>}
        {tail && <span className="receipt__seg">{tail}</span>}
      </p>
      {!solo && (
        <details className="receipt__more" open={open} onToggle={onToggle}>
          <summary>
            <span className="receipt__chev" aria-hidden="true"><Icon name="chev" size={12} /></span>
            How this was enforced
          </summary>
          <p className="t-body receipt__body">
            During capture, each observer&rsquo;s notes are readable only by that observer. The roster
            query returns names, colours and note counts, and never note bodies. Synthesis is the
            first and only read across lanes, and it runs on the server.
          </p>
        </details>
      )}
      <hr className="rule" style={{ marginTop: 'var(--space-6)' }} />
    </section>
  );
}
